services:
  - type: web
    name: inmobilike-it-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /healthz/
    envVars:
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: inmobilike-it-db
          property: connectionString

databases:
  - name: inmobilike-it-db
    plan: starter
    databaseName: inmobilike_it
    postgresMajorVersion: "16"
