# Generated by Codex on 2026-05-20

from django.db import migrations, models
from django.utils import timezone


def backfill_payment_invoices(apps, schema_editor):
    PropertyPayment = apps.get_model("properties", "PropertyPayment")

    paid_payments = PropertyPayment.objects.filter(
        status="paid",
        invoice_number__isnull=True,
    )
    for payment in paid_payments.iterator():
        issued_at = payment.paid_at or payment.created_at or timezone.now()
        payment.invoice_issued_at = issued_at
        payment.invoice_number = f"FAC-{issued_at:%Y%m%d}-{payment.pk:06d}"
        payment.save(update_fields=["invoice_number", "invoice_issued_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_alter_location_city_alter_location_neighborhood_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertypayment",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="propertypayment",
            name="invoice_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_payment_invoices, migrations.RunPython.noop),
    ]
